### ISSUE TITLE
.yml file to train from scratch

### ISSUE THREAD

**Issue by Mohgwyn** [monniert/unicorn#4]
Hi, your work is impressive and much appreciated.

I'm trying to train a model from scratch but, even though in the README appears a tutorial to do so, i think there are no examples of .yml files in which training from scratch is specified so i'm a bit lost. What do i have to include in the .yml to train from scratch?

**Comment by monniert** [comment]
Hi @Mohgwyn, thanks for the interest!

All configs in the `configs` folder are .yml files to train from scratch. What you need to do to train on a new custom dataset is:

1. To copy one of the file, e.g. car.yml to custom.yml
2. change the dataset name in the new yml (see the README last section for a quick dataloader setup)
3. change all training milestones to account for the new dataset size

As a rule of thumb, guidelines for the training milestones:
- related to progressing conditioning (i.e. in `deform_fields`, `texture_uv` and `background`): put the number of epochs corresponding to stages of 750k training iterations
- `freeze_T_predictor`, `freeze_shape` and `freeze_scale`: put the number of epochs corresponding to 10k, 20k and 250k iterations respectively
- `mean_txt`: put the same number as the start of the final training stage
- `n_epochs`: put the number of epochs corresponding to 3M iter

It is a bit cumbersome and I should have written the whole training pipeline in terms of iterations, this would have been much easier as all experiments basically share the same training setup

One thing I will try to do when I have time is to create a default config including all shared arguments (basically everything except the milestones) to make things simpler

**Comment by monniert** [comment]
I have pushed template config files (`custom.yml` and `custom_big.yml`) to train from scratch on a new custom dataset with the guidelines, hope this helps

**Comment by Mohgwyn** [comment]
It is much clearer now, thanks for your help this helps a lot.
